### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by tral**
Hi!
I'm from the XDA-forum (my nickname there is "tralchonok").

While I've been translating your xml, I notices that you use different app names there (Wifi PowerSaver & Wifi Better Battery).
I've changed it everywhere to "Wifi Better Battery", is it right?

Anyway, see the diff.

### CODE REVIEW

**Comment by CanisLupusXenonis** [comment]
Yes, thank you! WiFi PowerSave was the name before the "Better Battery" idea, I must have overlooked it in some places. Thank you!

**Comment by CanisLupusXenonis** [comment]
Don't you think it would be better to translate the app name too though?

**Comment by CanisLupusXenonis** [comment]
Oh, I just noticed - what you have so far is great, but the lib strings seem to be missing. WiFi Better Battery uses almost all of those. Also, I need a name to put into the Translators view!

**Comment by tral** [comment]
Ok, I thought that files are redundant))) will commit tomorrow

**Pull request merged**
