### PR TITLE
Play Store text translation into Russian. Fixes.

### PR DESCRIPTION
**Pull request by tral**
I also fixed some mistakes found.

### CODE REVIEW

**Comment by CanisLupusXenonis** [comment]
Awesome, thanks!

**Comment by tral** [comment]
Hi!
1) issue: When I tap op "Rate 5 stars in SP" you just open the Google Play Store. It's better to open your app's page directly. Here how to implement this: https://gist.github.com/tral/92a9e57e10e91db97e9f

2) The string "Change language" is not translated (and I don't see it in resources). See:
https://www.dropbox.com/s/b8g207fhxqlpnhq/2015-01-09%2011.13.22.png?dl=0

**Comment by tral** [comment]
1) it's in the DIALOG, which proposes to rate app, donate, etc
2)ok

**Comment by CanisLupusXenonis** [comment]
All right, thank you, I'll look into it.

2015-01-09 11:05 GMT+01:00 Aleksei Trubnikov <notifications@github.com>:

**Comment by CanisLupusXenonis** [comment]
Hey again,

I found a small problem in the translation:
prefLegacyDesc is too long to be displayed completely. It cuts off
after Активируйте эту опцию для того, чтобы иметь возможность.
Maybe you could shorten it a bit :)

2015-01-09 11:47 GMT+01:00 Michael Heissenberger <x3n0n.05@gmail.com>:

**Comment by tral** [comment]
ok, done

**Pull request merged**
