### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by kfahoo**
updated long description

### CODE REVIEW

**Comment by CanisLupusXenonis** [comment]
Honestly, I think the notice about turning off "scanning always available" is still necessary, as otherwise the WiFi will keep using full power. Any other way to shorten it?

**Comment by kfahoo** [comment]
transfer it to help?

**Comment by CanisLupusXenonis** [comment]
Hm, or maybe just remove the very last sentence, since that's already logical from the first part?

**Comment by kfahoo** [comment]
that was my idea before I checked russian translation, meaning of that
removed sentence is not exactly result of first sentence. some how it ought
be explained e.g. in help

2015-01-11 14:56 GMT+01:00 CanisLupusXenonis <notifications@github.com>:

**Pull request closed without merging**
