### PR TITLE
Create string.xml

### PR DESCRIPTION
**Pull request by Primokorn**

### CODE REVIEW

**Comment by CanisLupusXenonis** [comment]
Awesome, thank you. Would you please translate the setup strings too? Also, what name should I put into the translators view? :)

**Comment by Primokorn** [comment]
I guess everything has been translated. Let me know if I missed something.
Please use 'Primokorn' into the translators view. Thank you.

**Comment by CanisLupusXenonis** [comment]
Unless I'm overlooking something, the setup strings are missing.
I will, thank you too!

**Comment by CanisLupusXenonis** [comment]
Hey,

I really don't wanna seem impatient, just wanted to make sure you didn't
miss or forget about it - I'd still need the strings for the setup wizard
please.

Have a nice day!

2015-01-21 8:24 GMT+01:00 Primokorn <notifications@github.com>:

**Comment by Primokorn** [comment]
Sorry but I don't understand which you are talking about... Could you give me its directory?

**Comment by CanisLupusXenonis** [comment]
In wifi/values/strings.xml, I recently added a few new strings.
See this commit:
https://github.com/CanisLupusXenonis/MNDStrings/commit/db47e4f47f5cc58edafc4c8c96d5ba4257b64561
Would be great if you could translate those too :)

2015-01-26 13:49 GMT+01:00 Primokorn <notifications@github.com>:

**Pull request merged**
